dist: trusty
language: java
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.m2

install: ./mvnw -B clean validate

script:
  - ./mvnw -B -DskipTests=true install
  - ./mvnw -B verify
