dist: trusty
language: java
jdk:
  - oraclejdk9
cache:
  directories:
  - $HOME/.m2

before_install: 
  - git clone https://github.com/joinfaces/joinfaces.git
  - cd joinfaces
  - ./mvnw install -DskipTests=true -B

install: ./mvnw clean validate -B

script:
  - ./mvnw install -DskipTests=true -B 
  - ./mvnw verify -B

after_success:
  - "[[ ${TRAVIS_PULL_REQUEST} == 'false' ]] && ./mvnw -B org.eluder.coveralls:coveralls-maven-plugin:4.3.0:report"

notifications:
  email: false  