menu:
  items:
  - submenu: Administration
    subitems:
    - title: Options
      pageName: options
      icon: ui-icon-wrench
      isAjax: false
    - title: Users
      pageName: users
      icon: ui-icon-person
      isAjax: false
    - title: Roles and Rights
      pageName: rolesAndRights
      icon: ui-icon-key
      isAjax: false
  - submenu: Documents
    subitems:
    - title: Upload
      pageName: upload
      icon: ui-icon-circle-arrow-n
      isAjax: false
    - title: Download
      pageName: download
      icon: ui-icon-circle-arrow-s
      isAjax: false
