menu:
  items:
  - submenuTitle: Administration
    subitems:
    - title: Options
      pageName: options
      icon: ui-icon-wrench
      isAjax: false
    - title: Users
      pageName: users
      icon: ui-icon-person
      isAjax: false
    - title: Roles and Rights
      pageName: rolesAndRights
      icon: ui-icon-key
      isAjax: false
  - submenuTitle: Documents
    subitems:
    - title: Upload
      pageName: upload
      icon: ui-icon-circle-arrow-n
      isAjax: false
    - title: Download
      pageName: download
      icon: ui-icon-circle-arrow-s
      isAjax: false
  - submenuTitle: Start
    subitems:
    - title: Start
      pageName: main
      icon: ui-icon-circle-arrow-s
      isAjax: false
    - title: MasterDetail
      pageName: masterDetail
      icon: ui-icon-circle-arrow-s
      isAjax: false
    - title: Car List
      pageName: carList
      icon: ui-icon-key
      isAjax: false