package org.philmaster.boot.beans;

import javax.annotation.PostConstruct;
import javax.enterprise.context.ApplicationScoped;
import javax.inject.Named;

import org.apache.cayenne.ObjectContext;
import org.apache.cayenne.configuration.server.ServerRuntime;

/**
 * @author Philmasteryeah
 * 
 *         This class uses the database scheme which is generated by the cayenne
 *         modeler.
 * 
 *         pure jdbc example: 
 *         JdbcTemplate jdbcTemplate;
 *         jdbcTemplate.update("INSERT INTO car(brand)VALUES(?)", "Honda"));
 * 
 *         orm cayenne example:
 *         ObjectContext ctx = dbBean.getContext(); 
 *         Cars car  = ctx.newObject(Cars.class);
 *         car.setName("test car");
 *         ctx.commitChanges();
 *
 */

@Named
@ApplicationScoped
public class DatabaseBean {

    private static final String CAYENNE_CONFIG = "cayenne-project.xml";

    private ObjectContext context;

    public ObjectContext getContext() {
	return context;
    }

    public void setContext(ObjectContext context) {
	this.context = context;
    }

    @PostConstruct
    void init() {
	context = ServerRuntime.builder().addConfig(CAYENNE_CONFIG).build().newContext();
    }

}
