package org.philmaster.boot.service;

import java.time.DayOfWeek;
import java.util.ArrayList;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.enterprise.context.ApplicationScoped;
import javax.inject.Named;

import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.select.Elements;
import org.philmaster.boot.model.Meal;

/**
 * @author Philmasteryeah
 * 
 *         This class uses the database scheme which is generated by the cayenne
 *         modeler.
 * 
 *         pure jdbc example: JdbcTemplate jdbcTemplate;
 *         jdbcTemplate.update("INSERT INTO car(brand)VALUES(?)", "Honda"));
 * 
 *         orm cayenne example: ObjectContext ctx = dbBean.getContext(); Cars
 *         car = ctx.newObject(Cars.class); car.setName("test car");
 *         ctx.commitChanges();
 *
 */

@Named
@ApplicationScoped
public class FoodService {

	private static final String URL = "https://www.bestellung-rastenberger.de/index.php";

	@PostConstruct
	void init() {
	}

	public List<Meal> getParsedMeals() throws Exception {
		Document doc = Jsoup.connect(URL).get();
		Elements menuRows = doc.getElementsByClass("splanauflistung").get(0).select("tbody").get(0).select("tr");

		List<Meal> meals = new ArrayList<>();

		for (int i = 1; i < menuRows.size(); i++) {
			Elements rows = menuRows.get(i).select("td");
			String type = rows.get(0).text(); // Menü Typ z.B. Eintopf

			// über tage iterieren rows.size() durch 5 ersetzt bis Freitag
			for (int dayIndex = 1; dayIndex < 5; dayIndex++) {
				String desc = rows.select("td").get(dayIndex).text();
				DayOfWeek day = DayOfWeek.of(dayIndex);
				float price = 0.0f; // TODO
				Meal meal = new Meal(day, type, desc, price);
				meals.add(meal);
			}

			// meals.forEach(System.err::println);

		}
		return meals;

	}

}
